In [3]:
import numpy as np
import sys
import commpy
import struct
import matplotlib.pyplot as plt
import scipy

from LoRaDecoder import LoRaDecoder

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [22]:
rf_freq = 915e6    # carrier frequency 470 MHz, used to correct clock drift
sf = 8             # spreading factor SF7
bw = 125e3         # bandwidth 125 kHz
fs = 250e3         # sampling rate 1 MHz

phy = LoRaDecoder()



phy.chirp(True,sf,bw,fs,0,0,0)

(512,)
512
(50,)


In [16]:
a = np.array(range(5))
print(a)
print(a*a)
print(a**2)

[0 1 2 3 4]
[ 0  1  4  9 16]
[ 0  1  4  9 16]
